services:
  deepseek-ocr:
    build: .
    container_name: deepseek-ocr-vllm
    ports:
      - "8000:8000"
    volumes:
    #  - ./models:/app/models  # Mount directory for model weights
      - ./outputs:/app/outputs  # Mount directory for output files
      - ./test_input.json:/app/test_input.json
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - MODEL_PATH=/app/models/deepseek-ai/DeepSeek-OCR  # Update with your model path
      - MAX_CONCURRENCY=5  # Adjust based on your GPU memory
      - GPU_MEMORY_UTILIZATION=0.85  # Adjust based on your GPU memory
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: no